# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('suffix', models.CharField(max_length=2, unique=True)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='conversion factor from kilometers')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('S', 'Start'), ('F', 'Finish'), ('P', 'Pause'), ('R', 'Resume'), ('A', 'Active')], max_length=1)),
                ('time', models.DateTimeField()),
                ('elevation', models.DecimalField(decimal_places=2, max_digits=7)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('pace', models.BooleanField(default=True)),
                ('distance_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.Distance_Unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('file_hash', models.CharField(max_length=32, unique=True, verbose_name='md5 hash value')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start date and time')),
                ('finish', models.DateTimeField(blank=True, null=True, verbose_name='finish date and time')),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='total moving time in hours')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='total moving distance in kilometers')),
                ('average_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='average moving speed in kilometers per hour')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.AddField(
            model_name='point',
            name='gpx_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Track'),
        ),
    ]
