# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170626_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='TrackPoint',
        ),
    ]
