# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170626_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackpoint',
            name='track',
        ),
        migrations.DeleteModel(
            name='TrackPoint',
        ),
    ]
